# .github/workflows/ci-backend-express.yml
name: Backend-Express CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./backend-express

    - name: Run tests
      run: npm run test
      working-directory: ./backend-express
      env:
        NODE_ENV: test
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        MONGO_DB_URI: ${{ secrets.MONGO_DB_URI }}

    - name: Build (optional if you have build step)
      run: npm run build --if-present
      working-directory: ./backend-express
